In [77]:
#eg 2.1-2.2 perceptron learning algorithm
import numpy as np

x=np.array([[3, 3],
            [4, 3],
            [1, 1]])
y=np.array([1, 1, -1])

In [78]:
def original_learning():
    w0_1 = 0
    w0_2 = 0
    b0 = 0
    learning_rate = 1
    count = 0

    while count < x.shape[0]:
        for i in range(0, x.shape[0]):
            if y[i] * (w0_1 * x[i,0] + w0_2 * x[i,1] + b0)<=0:
                w0_1 += learning_rate * y[i] * x[i, 0]
                w0_2 += learning_rate * y[i] * x[i, 1]
                b0 += learning_rate * y[i]
                count = 0
                print(w0_1, w0_2, b0)
            else:
                count += 1

    print("y=sign("+str(w0_1)+"*x0+"+str(w0_2)+"*x1+"+str(b0)+")")
    return

In [79]:
def dual_learning():
    alpha=np.zeros(x.shape[0])
    b0 = 0
    learning_rate = 1
    w0_1 = 0
    w0_2 = 0
    count = 0
    
    gram=np.zeros((x.shape[0], x.shape[0]))
    for i in range(0, x.shape[0]):
        for j in range(0, x.shape[0]):
            gram[i, j]=x[i, 0]*x[j, 0]+x[i, 1]*x[j, 1]
    print(gram)
    
    while count < x.shape[0]:
        for i in range(0,x.shape[0]):
            dual_value = 0
            for j in range(0, x.shape[0]):
                dual_value += alpha[j] * y[j] * gram[j, i]
            dual_value += b0
            dual_value *= y[i]
            if dual_value <= 0:
                alpha[i] += learning_rate
                b0 += learning_rate * y[i]
                count = 0
                print(alpha, b0)
            else:
                count += 1
    
    for i in range(0, x.shape[0]):
        w0_1 += alpha[i] * y[i] * x[i, 0]
        w0_2 += alpha[i] * y[i] * x[i, 1]
        #b0 += alpha[i] * y[i]
    print("y=sign("+str(w0_1)+"*x0+"+str(w0_2)+"*x1+"+str(b0)+")")
    return

In [76]:
if __name__=="__main__":
    original_learning()
    dual_learning()

3 3 1
2 2 0
1 1 -1
0 0 -2
3 3 -1
2 2 -2
1 1 -3
y=sign(1*x0+1*x1+-3)
[[18. 21.  6.]
 [21. 25.  7.]
 [ 6.  7.  2.]]
[1. 0. 0.] 1
[1. 0. 1.] 0
[1. 0. 2.] -1
[1. 0. 3.] -2
[2. 0. 3.] -1
[2. 0. 4.] -2
[2. 0. 5.] -3
y=sign(1.0*x0+1.0*x1+-3)
